// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AuthenticateController from "./authenticate_controller"
application.register("authenticate", AuthenticateController)

import EmojiPickerController from "./emoji_picker_controller"
application.register("emoji-picker", EmojiPickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageDecryptorController from "./message_decryptor_controller"
application.register("message-decryptor", MessageDecryptorController)

import MessageEncryptorController from "./message_encryptor_controller"
application.register("message-encryptor", MessageEncryptorController)

import ReauthController from "./reauth_controller"
application.register("reauth", ReauthController)
